# Generated by Django 5.1.1 on 2024-12-19 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс для оказание услуг')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('desired_date', models.DateTimeField(null=True, verbose_name='Дата и время')),
                ('payment_type', models.CharField(choices=[('cash', 'Оплата наличными'), ('card', 'Оплата банковской картой')], default='cash', max_length=100, verbose_name='Способ оплаты')),
                ('service', models.CharField(choices=[('common_clean', 'Общий клининг'), ('full_clean', 'Генеральная уборка'), ('post_cons_cleaning', 'Послестроительная уборка'), ('dry_cleaning', 'Химчистка')], max_length=100, verbose_name='Услуги')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'Выполняется'), ('completed', 'Услуга оказана'), ('cancelled', 'Услуга отменена')], default='new', max_length=100, verbose_name='Статус заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
    ]
